#!/usr/bin/env python

Import("env")
Import("env_modules")

env_tile = env_modules.Clone()

# Godot's own source files
env_tile.add_source_files(env.modules_sources, "*.cpp")
if env["tools"]:
    env_tile.add_source_files(env.modules_sources, "editor/*.cpp")
